/**
 * This file is auto-generated by the build script.
 * It consolidates API functions for use in the application.
 * Do not edit manually.
 */
import _edge_add from './src/edge/add.js';
import _edge_addMultiple from './src/edge/addMultiple.js';
import _edge_addToSuperNode from './src/edge/addToSuperNode.js';
import _edge_convertToSuperNode from './src/edge/convertToSuperNode.js';
import _edge_delete from './src/edge/delete.js';
import _edge_deleteFromSuperNode from './src/edge/deleteFromSuperNode.js';
import _edge_deleteMultiple from './src/edge/deleteMultiple.js';
import _edge_getMultiple from './src/edge/getMultiple.js';
import _edge_search from './src/edge/search.js';
import _kv_add from './src/kv/add.js';
import _kv_addMultiple from './src/kv/addMultiple.js';
import _kv_delete from './src/kv/delete.js';
import _kv_deleteMultiple from './src/kv/deleteMultiple.js';
import _kv_get from './src/kv/get.js';
import _kv_getMultiple from './src/kv/getMultiple.js';
import _vertex_add from './src/vertex/add.js';
import _vertex_addMultiple from './src/vertex/addMultiple.js';
import _vertex_delete from './src/vertex/delete.js';
import _vertex_deleteMultiple from './src/vertex/deleteMultiple.js';
import _vertex_get from './src/vertex/get.js';
import _vertex_getMultiple from './src/vertex/getMultiple.js';


export default {
    edge: {
        /**
         * Adds a single item by wrapping it in an array and passing it to the addMultiple function.
         *
         * @param {Object} item - The item to be added, represented as an array [vertex1, edgeType, vertex2].
         * 
         * @returns {Promise<Object>} A promise that resolves to the added item.
         *
         * @example
         * const item = ['vertex1', 'edgeType', 'vertex2'];
         * add(item).then(addedItem => {
         *   console.log(addedItem);
         * });
         */
        add: _edge_add,
        addMultiple: _edge_addMultiple,
        addToSuperNode: _edge_addToSuperNode,
        convertToSuperNode: _edge_convertToSuperNode,
        delete: _edge_delete,
        deleteFromSuperNode: _edge_deleteFromSuperNode,
        deleteMultiple: _edge_deleteMultiple,
        getMultiple: _edge_getMultiple,
        search: _edge_search,
    },
    kv: {
        add: _kv_add,
        addMultiple: _kv_addMultiple,
        delete: _kv_delete,
        deleteMultiple: _kv_deleteMultiple,
        get: _kv_get,
        getMultiple: _kv_getMultiple,
    },
    vertex: {
        add: _vertex_add,
        addMultiple: _vertex_addMultiple,
        delete: _vertex_delete,
        deleteMultiple: _vertex_deleteMultiple,
        get: _vertex_get,
        getMultiple: _vertex_getMultiple,
    },
};